name: test

channels:
    - conda-forge
    - defaults

dependencies:
    - python=3.6
    - numpy
    - matplotlib
    - pandas
    - xlrd
    - geojsonio
    - seaborn
    - nb_conda
    - pytables
#    - h5py                  # Should this be here?
    - scikit-learn
    - scipy
    - cython

    - pip:
        - watermark
        - shapely
        - geopandas
#        - cartopy           # Should this be here?
