name: oakland

channels:
    - conda-forge
    - defaults

dependencies:
    - appnope=0.1.0=py36_0
    - asn1crypto=0.22.0=py36_0
    - backports=1.0=py36_1
    - backports.functools_lru_cache=1.4=py36_1
    - basemap=1.1.0=py36_3
    - blas=1.1=openblas
    - bleach=2.0.0=py36_0
    - bzip2=1.0.6=1
    - ca-certificates=2017.11.5=0
    - cairo=1.14.6=5
    - certifi=2017.11.5=py36_0
    - cffi=1.10.0=py36_0
    - chardet=3.0.4=py36_0
    - click=6.7=py36_0
    - click-plugins=1.0.3=py36_0
    - cligj=0.4.0=py36_0
    - cryptography=2.0.3=py36_0
    - curl=7.55.1=0
    - cycler=0.10.0=py36_0
    - decorator=4.1.2=py36_0
    - descartes=1.1.0=py36_0
    - entrypoints=0.2.3=py36_1
    - expat=2.1.0=3
    - fontconfig=2.12.1=5
    - freetype=2.7=2
    - freexl=1.0.2=2
    - geojsonio=0.0.3=py_0
    - geos=3.6.2=1
    - geotiff=1.4.2=0
    - gettext=0.19.8.1=0
    - giflib=5.1.4=0
    - github3.py=1.0.0a4=py36_0
    - glib=2.51.4=0
    - h5py=2.7.1=py36_2
    - hdf4=4.2.13=0
    - hdf5=1.10.1=1
    - html5lib=0.999999999=py36_0
    - icu=58.2=0
    - idna=2.6=py36_1
    - ipykernel=4.6.1=py36_0
    - ipyleaflet=0.5.2=py36_0
    - ipython=6.2.1=py36_0
    - ipython_genutils=0.2.0=py36_0
    - ipywidgets=7.0.5=py36_0
    - jedi=0.10.2=py36_0
    - jinja2=2.9.6=py36_0
    - jpeg=9b=2
    - json-c=0.12.1=0
    - jsonschema=2.6.0=py36_0
    - jupyter_client=5.1.0=py36_0
    - jupyter_core=4.4.0=py_0
    - kealib=1.4.7=4
    - krb5=1.14.2=0
    - libdap4=3.18.3=2
    - libffi=3.2.1=3
    - libgfortran=3.0.0=0
    - libiconv=1.14=4
    - libkml=1.3.0=3
    - libnetcdf=4.4.1.1=10
    - libpng=1.6.28=2
    - libpq=9.6.3=0
    - libsodium=1.0.15=1
    - libspatialindex=1.8.5=1
    - libssh2=1.8.0=2
    - libtiff=4.0.7=1
    - libxml2=2.9.5=1
    - markupsafe=1.0=py36_0
    - matplotlib=2.1.0=py36_1
    - mistune=0.8=py36_0
    - munch=2.2.0=py36_0
    - nb_conda=2.2.1=py36_0
    - nb_conda_kernels=2.1.0=py36_0
    - nbconvert=5.3.1=py_1
    - nbformat=4.4.0=py36_0
    - ncurses=5.9=10
    - notebook=5.2.1=py36_2
    - numexpr=2.6.4=py36_0
    - numpy=1.13.3=py36_blas_openblas_201
    - openblas=0.2.20=4
    - openjpeg=2.1.2=2
    - openssl=1.0.2l=0
    - pandas=0.21.0=py36_0
    - pandoc=2.0.0.1=1
    - pandocfilters=1.4.1=py36_0
    - patsy=0.4.1=py36_0
    - pcre=8.39=0
    - pexpect=4.3.0=py36_0
    - pickleshare=0.7.4=py36_0
    - pip=9.0.1=py36_0
    - pixman=0.34.0=0
    - poppler=0.52.0=3
    - poppler-data=0.4.7=0
    - proj4=4.9.3=5
    - prompt_toolkit=1.0.15=py36_0
    - psycopg2=2.7.3.2=py36_0
    - ptyprocess=0.5.2=py36_0
    - pyasn1=0.3.7=py_0
    - pycparser=2.18=py36_0
    - pygments=2.2.0=py36_0
    - pyopenssl=17.2.0=py36_0
    - pyparsing=2.2.0=py36_0
    - pyproj=1.9.5.1=py36_0
    - pysal=1.14.3=py36_0
    - pyshp=1.2.12=py_0
    - pysocks=1.6.7=py36_0
    - pytables=3.4.2=py36_7
    - python=3.6.3=1
    - python-dateutil=2.6.1=py36_0
    - pytz=2017.3=py_2
    - pyzmq=16.0.2=py36_2
    - readline=6.2=0
    - requests=2.18.4=py36_1
    - rtree=0.8.3=py36_0
    - scikit-learn=0.19.1=py36_blas_openblas_201
    - scipy=1.0.0=py36_blas_openblas_201
    - seaborn=0.8.1=py36_0
    - setuptools=36.7.2=py36_0
    - simplegeneric=0.8.1=py36_0
    - six=1.11.0=py36_1
    - sqlalchemy=1.1.13=py36_0
    - sqlite=3.13.0=1
    - statsmodels=0.8.0=py36_0
    - terminado=0.6=py36_0
    - testpath=0.3.1=py36_0
    - tk=8.5.19=2
    - tornado=4.5.2=py36_0
    - traitlets=4.3.2=py36_0
    - uritemplate.py=3.0.2=py36_0
    - urllib3=1.22=py36_0
    - wcwidth=0.1.7=py36_0
    - webencodings=0.5=py36_0
    - wheel=0.30.0=py_1
    - widgetsnbextension=3.0.8=py36_0
    - xerces-c=3.1.4=3
    - xlrd=1.1.0=py36_1
    - xz=5.2.3=0
    - zeromq=4.2.1=1
    - zlib=1.2.11=0
    - cython=0.26.1=py36hd51f8eb_0

    - pip:
          - attrs==17.3.0
          - backports.functools-lru-cache==1.4
          - cartopy==0.15.1
          - enum34==1.1.6
          - fiona==1.7.10.post1
          - flask==0.12.2
          - geopandas==0.3.0
          - ipython-genutils==0.2.0
          - itsdangerous==0.24
          - jupyter-client==5.1.0
          - jupyter-core==4.4.0
          - lxml==4.1.1
          - markdown==2.6.9
          - nb-conda==2.2.1
          - nb-conda-kernels==2.1.0
          - pluggy==0.6.0
          - prompt-toolkit==1.0.15
          - protobuf==3.5.0.post1
          - py==1.5.2
          - pytest==3.3.1
          - shapely==1.6.2.post1
          - tables==3.4.2
          - tensorflow==1.4.0
          - tensorflow-tensorboard==0.4.0rc3
          - uritemplate==2.0.0
          - watermark==1.5.0
          - werkzeug==0.12.2
